const $=s=>document.querySelector(s);
const shared=["mandrillapp.com","sendgrid.net","mailgun.org","docusign.net","docusign.com","sharepoint.com","docs.google.com","drive.google.com","safelinks.protection.outlook.com"];
const prov=[["SharePoint / OneDrive",/\.sharepoint\.com$/i],["Google Drive / Docs",/(docs|drive)\.google\.com$/i],["DocuSign",/\.?docusign\.(net|com)$/i],["Microsoft Safe Links",/safelinks\.protection\.outlook\.com$/i],["Mandrill",/mandrillapp\.com$/i],["SendGrid",/sendgrid\.net$/i],["Mailgun",/mailgun\.(org|net)$/i]];
const isShared=h=>shared.some(x=>h===x||h.endsWith("."+x));
const provider=h=>(prov.find(x=>x[1].test(h))||["Generic / unknown"])[0];
function embedded(t){return [...new Set((t.match(/https?:\/\/[^\s"'<>]+/gi)||[]).map(x=>{try{return new URL(x).hostname}catch{return null}}).filter(Boolean))]}
function analyze(raw){let u;try{u=new URL(raw)}catch{return {raw,error:1}};let h=u.hostname.toLowerCase(),p=provider(h),c=[],n=[["Shared provider",p,"Same public service is NOT sender linkage."]];
if(p==="SharePoint / OneDrive"){let t=h.replace(/-my\.sharepoint\.com$/,"").replace(/\.sharepoint\.com$/,"");if(t)c.push(["SharePoint tenant",t,"HIGH","Reusable tenant namespace; useful correlation clue."]);let m=u.pathname.match(/\/personal\/([^/]+)/i);if(m)c.push(["OneDrive namespace",m[1],"MEDIUM","Reusable namespace; not proof of sender identity."])}
if(p==="Google Drive / Docs"){let id=u.pathname.match(/\/d\/([^/]+)/)?.[1]||u.searchParams.get("id");if(id)c.push(["Google resource ID",id,"MEDIUM","Good pivot for reuse of the same resource; not a Google account ID."])}
let parts=[u.pathname,...[...u.searchParams.values()]], dec=[];for(let x of parts){for(let i=0;i<3;i++){try{let y=decodeURIComponent(x);dec.push(y);if(y===x)break;x=y}catch{break}}}
for(let d of [...new Set(dec.flatMap(embedded))].filter(x=>x!==h))c.push(["Embedded / downstream domain",d,isShared(d)?"LOW":"HIGH",isShared(d)?"Shared infrastructure; context only.":"Distinct downstream domain; useful hunting pivot."]);
if(p==="Generic / unknown"&&!isShared(h))c.push(["Observed host",h,"MEDIUM","Distinct host; role unknown until correlated."]);
for(let [k,v] of u.searchParams){if(/campaign|account|tenant|portal|client|brand|site/i.test(k)&&v.length<180)c.push(["Named parameter "+k,v,"MEDIUM","Semantically relevant reusable-ID candidate; verify by repetition."]);else if(/recipient|email|user|timestamp|time|token|signature|sig|nonce/i.test(k))n.push(["Suppressed "+k,v,"Likely per-message/recipient noise."])}
return {raw,h,p,c,n}}
function esc(s){return String(s).replace(/[&<>"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[x]))}
function render(x){if(x.error)return `<div class=card>Invalid URL<div class=value>${esc(x.raw)}</div></div>`;return `<div class=card><h3>${esc(x.p)}</h3><div class=value>${esc(x.h)}</div>${x.c.length?x.c.map(a=>`<div class="clue ${a[2].toLowerCase()}"><b>${esc(a[0])} · ${a[2]}</b><div class=value>${esc(a[1])}</div><div class=why>${esc(a[3])}</div></div>`).join(""):"<p>No distinctive sender-side clue supported by this URL.</p>"}<details><summary>Ignored/context</summary>${x.n.map(a=>`<div class="clue noise"><b>${esc(a[0])}</b><div class=why>${esc(a[2])}</div></div>`).join("")}</details></div>`}
function compare(){let a=JSON.parse(localStorage.getItem("cc")||"[]"),m=new Map();a.forEach((x,i)=>x.c.filter(y=>y[2]!=="LOW").forEach(y=>{let k=y[0]+"|"+y[1];m.set(k,(m.get(k)||new Set()).add(i))}));let r=[...m].filter(x=>x[1].size>1).sort((a,b)=>b[1].size-a[1].size);$("#compare").innerHTML=r.length?r.map(([k,v])=>{let [t,x]=k.split("|");return `<div class=clue><b>${esc(t)}</b><div class=value>${esc(x)}</div><div class=why>Repeated in ${v.size} analyses. Correlation clue only — not proof of common operator.</div></div>`}).join(""):"<p>No distinctive repeated clues yet.</p>"}
$("#go").onclick=()=>{let r=$("#urls").value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(analyze);$("#out").innerHTML=r.map(render).join("");let old=JSON.parse(localStorage.getItem("cc")||"[]");localStorage.setItem("cc",JSON.stringify(old.concat(r.filter(x=>!x.error)).slice(-200)));compare()};$("#clear").onclick=()=>{localStorage.removeItem("cc");compare()};compare();